#!/usr/bin/env python
"""IBKR Integration Setup and Test"""

from src.ibkr_connector import IBKRConnector

print('IBKR Connector initialized successfully!')
print()
print('='*70)
print('IBKR INTEGRATION SETUP GUIDE')
print('='*70)
print()
print('Step 1: Download and Install')
print('  - Download TWS or IBGateway')
print('  - From: https://www.interactivebrokers.com')
print()
print('Step 2: Configure Connection Settings')
print('  Paper Trading:   Port 7497')
print('  Live Trading:    Port 7496')
print()
print('Step 3: Enable API Connections')
print('  - Open TWS/IBGateway')
print('  - Go to: File > Global Configuration')
print('  - API > Settings')
print('  - Enable ActiveX and Socket Clients')
print()
print('Step 4: Run Trading Scripts')
print('  # Get live predictions:')
print('  python predict_ibkr_live.py')
print()
print('  # Execute trades:')
print('  python trade_with_ibkr.py')
print()
print('  # Demo IBKR connection:')
print('  python -m src.ibkr_connector')
print()
print('='*70)
